### ISSUE TITLE
Won't compile on OpenSuse Leap 15.2

### ISSUE THREAD

**Issue by richardeigenmann** [jtsiomb/xlivebg#5]
Enjoyed your Fosdem talk. Thanks.

I'm having trouble compiling this on OpenSuse Leap 15.2. 

I have avcodec.h installed in 
/usr/include/ffmpeg/libavcodec/avcodec.h

./configure doesn't complain.
But make does:

make[2]: Entering directory '/richi/ToDo/xlivebg/plugins/video'
cc -pedantic -Wall -g -O3 -ffast-math -fPIC -I../../include  -Wno-deprecated-declarations -pthread   -c -o vid.o vid.c
vid.c:22:10: fatal error: libavcodec/avcodec.h: No such file or directory
 #include <libavcodec/avcodec.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

How to fix?

**Comment by jtsiomb** [comment]
The problem seems to be that opensuse installs the ffmpeg header files under an extra `ffmpeg` directory, which isn't in the include path. For now, adding `-I/usr/include/ffmpeg` to the `plugin_cflags` line of `plugins/video/Makefile` should fix it. But I'll probably have to add a call to pkg-config for this.

Otherwise if you don't care about the video plugin you can just disable it by passing `--disable-plugin-video` to `configure`.

**Comment by jtsiomb** [comment]
You could also do that with extra CFLAGS when running configure, instead of modifying the plugin makefile: `CFLAGS=-I/usr/include/ffmpeg ./configure`. That should also work.

**Comment by richardeigenmann** [comment]
For the record:
I had to install these packages on OpenSuse Leap 15.2 before it would compile:
sudo zypper in ffmpeg-4-libavcodec-devel ffmpeg-4-libavformat-devel ffmpeg-4-libswscale-devel motif-devel

I modified the plugins/video/Makefile file and added the -I/usr/include/ffmpeg at the end of this line:
plugin_cflags = -Wno-deprecated-declarations -pthread -I/usr/include/ffmpeg

I think the configure script should look and check for these headers that the compile failed on for me:
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libswscale/swscale.h>
#include <Xm/Xm.h>

Oddly, the suggestion to set the environment CFLAGS variable didn't work.

Now that the program is compiled and working, I am disappointed to report that nothing is happening on my background. I suppose the code is not properly identifying the correct root window. xpenguins also doesn't do anything so I must be running something special. I am on KDE. $XDG_SESSION_TYPE reports I am on x11. xeyes does work.

**Comment by jtsiomb** [comment]
Yes, for KDE you need to start xlivebg with `-n`.

The reason configure doesn't check for ffmpeg and motif is because these are conceptually separate things, you don't necessarilly need to compile the video plugin, or the GUI config program. But it might be a good idea to add a mechanism for checking the dependencies of the enabled plugins at some point.

**Comment by richardeigenmann** [comment]
./xlivebg -n Does the trick. Pretty cool!
Clicking on video in the gui is a bit temperamental. I need to kill the program from the process table and rm /tmp/xlivebg.sock before it will restart. Probably the right kind of video is required. ffplay does play the videos I selected. The plugin probably needs a bit of extra error checking so that it doesn't bring down the program and hang the gui window. 
It might be an idea to include the samples you were showing in a /samples directory in the repo.

**Comment by DavidBonelo** [comment]
Same problem on Fedora 34 KDE
as mentioned, I edited the `plugins/video/Makefile` file and it worked.
now, launching xlivebg with `-n` all the plugins work, except for the video plugin.
```
yeru@fedora ~> xlivebg -n
Using config file: /home/yeru/.config/xlivebg.conf
detected 1 outputs:
 [0] HDMI-A-0: 1920x1080+0+0
xlivebg: searching for plugins in /usr/local/lib/xlivebg
xlivebg: registered plugin: ripple
xlivebg: registered plugin: stars
xlivebg: registered plugin: colcycle
xlivebg: registered plugin: distort
xlivebg: registered plugin: video
xlivebg: activating plugin: video
window size: 1920x1080
window visual: 517
 double-buffered RGBA 888, 24 bits zbuffer
using codec: h264
fps: 60.000000 (16666 usec frame interval)
size: 1920x1008
^C^C^C
```
I tried with different videos, but I only get a black screen as wallpaper, and I have to kill the process to stop it

**Comment by jtsiomb** [comment]
60 fps is way too much. Even if the plugin worked correctly, it would eat up all your CPU time. Try with 25 or 30fps videos ideally.

Having said that, it should be able to play it back, assuming your processor is fast enough to decode it in real time.

My real suggestion is to forget about the video plugin. I should probably remove it altogether. I just included it for the flexibility it provides, but really it's not worth spending so much CPU time to show something moving on the desktop.

**Comment by DavidBonelo** [comment]
true, 60fps was just a test haha, I tried different video length, fps, resolutions, codec, without audio, but nothing.
> My real suggestion is to forget about the video plugin. I should probably remove it altogether.

Ok 😔, but now I need instructions on how to uninstall lol

**Comment by jtsiomb** [comment]
Yes, there is `uninstall` (for the main xlivebg program and header files), `uninstall-plugins`, and `uninstall-gui`. `uninstall-all` does all of the above.

**Comment by jtsiomb** [comment]
Commit 94dca6ac398f473d7ecf46bdec63103ef784190e adds improved dependency checking in the configure script. If motif headers are missing, it disables building the GUI, and if ffmpeg headers are missing, it disables building the video plugin. In both cases the user is notified at configure time of the missing dependencies and how they will impact the build.

This fix closes this bug report. For bugs in the video plugin, please open a separate issue.
